[package]
name = "substreams"
version.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1"
bytes = "1"
buffa-types = { version = "0.9", default-features = false, features = ["std"] }
bigdecimal = "0.4"
hex = "0.4"
hex-literal = "0.3"
num-bigint = "0.4"
num-traits = "0.2"
num-integer = "0.1.45"
pad = "0.1"
buffa = { version = "0.9", default-features = false, features = ["std", "fast-utf8"] }
substreams-macro = { workspace = true }
thiserror = "1"
pest = "2.7.10"
pest_derive = "2.7.10"

[dev-dependencies]
rstest = "0.19.0"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "expr_parser_bench"
harness = false
