// @generated by buffa-codegen. DO NOT EDIT.
// source: sf/substreams/v1/modules.proto

pub mod module {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum Kind<'a> {
        KindMap(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::module::KindMapView<'a>,
            >,
        ),
        KindStore(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::module::KindStoreView<'a>,
            >,
        ),
        KindBlockIndex(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::module::KindBlockIndexView<'a>,
            >,
        ),
    }
    pub mod block_filter {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Clone, Debug)]
        pub enum Query<'a> {
            QueryString(&'a str),
            QueryFromParams(
                ::buffa::alloc::boxed::Box<
                    super::super::super::super::super::__buffa::view::module::QueryFromParamsView<
                        'a,
                    >,
                >,
            ),
        }
    }
    pub mod input {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Clone, Debug)]
        pub enum Input<'a> {
            Source(
                ::buffa::alloc::boxed::Box<
                    super::super::super::super::super::__buffa::view::module::input::SourceView<
                        'a,
                    >,
                >,
            ),
            Map(
                ::buffa::alloc::boxed::Box<
                    super::super::super::super::super::__buffa::view::module::input::MapView<
                        'a,
                    >,
                >,
            ),
            Store(
                ::buffa::alloc::boxed::Box<
                    super::super::super::super::super::__buffa::view::module::input::StoreView<
                        'a,
                    >,
                >,
            ),
            Params(
                ::buffa::alloc::boxed::Box<
                    super::super::super::super::super::__buffa::view::module::input::ParamsView<
                        'a,
                    >,
                >,
            ),
            FoundationalStore(
                ::buffa::alloc::boxed::Box<
                    super::super::super::super::super::__buffa::view::module::FoundationalStoreView<
                        'a,
                    >,
                >,
            ),
        }
    }
}
