// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRequest {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag="3")]
    pub keys: ::prost::alloc::vec::Vec<super::super::model::v2::Key>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetResponse {
    #[prost(bool, tag="1")]
    pub block_reached: bool,
    #[prost(message, optional, tag="2")]
    pub entries: ::core::option::Option<super::super::model::v2::QueriedEntries>,
}
// @@protoc_insertion_point(module)
