// @generated by buffa-codegen. DO NOT EDIT.
// source: sf/substreams/v1/modules.proto

pub mod module {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    pub enum Kind {
        KindMap(::buffa::alloc::boxed::Box<super::super::super::module::KindMap>),
        KindStore(::buffa::alloc::boxed::Box<super::super::super::module::KindStore>),
        KindBlockIndex(
            ::buffa::alloc::boxed::Box<super::super::super::module::KindBlockIndex>,
        ),
    }
    impl ::buffa::Oneof for Kind {}
    impl From<super::super::super::module::KindMap> for Kind {
        fn from(v: super::super::super::module::KindMap) -> Self {
            Self::KindMap(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::module::KindMap> for ::core::option::Option<Kind> {
        fn from(v: super::super::super::module::KindMap) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::module::KindStore> for Kind {
        fn from(v: super::super::super::module::KindStore) -> Self {
            Self::KindStore(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::module::KindStore> for ::core::option::Option<Kind> {
        fn from(v: super::super::super::module::KindStore) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::module::KindBlockIndex> for Kind {
        fn from(v: super::super::super::module::KindBlockIndex) -> Self {
            Self::KindBlockIndex(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::module::KindBlockIndex>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::module::KindBlockIndex) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    pub mod block_filter {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Clone, PartialEq, Debug)]
        pub enum Query {
            QueryString(::buffa::alloc::string::String),
            QueryFromParams(
                ::buffa::alloc::boxed::Box<
                    super::super::super::super::module::QueryFromParams,
                >,
            ),
        }
        impl ::buffa::Oneof for Query {}
        impl From<super::super::super::super::module::QueryFromParams> for Query {
            fn from(v: super::super::super::super::module::QueryFromParams) -> Self {
                Self::QueryFromParams(::buffa::alloc::boxed::Box::new(v))
            }
        }
        impl From<super::super::super::super::module::QueryFromParams>
        for ::core::option::Option<Query> {
            fn from(v: super::super::super::super::module::QueryFromParams) -> Self {
                Self::Some(Query::from(v))
            }
        }
    }
    pub mod input {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Clone, PartialEq, Debug)]
        pub enum Input {
            Source(
                ::buffa::alloc::boxed::Box<
                    super::super::super::super::module::input::Source,
                >,
            ),
            Map(
                ::buffa::alloc::boxed::Box<
                    super::super::super::super::module::input::Map,
                >,
            ),
            Store(
                ::buffa::alloc::boxed::Box<
                    super::super::super::super::module::input::Store,
                >,
            ),
            Params(
                ::buffa::alloc::boxed::Box<
                    super::super::super::super::module::input::Params,
                >,
            ),
            FoundationalStore(
                ::buffa::alloc::boxed::Box<
                    super::super::super::super::module::FoundationalStore,
                >,
            ),
        }
        impl ::buffa::Oneof for Input {}
        impl From<super::super::super::super::module::input::Source> for Input {
            fn from(v: super::super::super::super::module::input::Source) -> Self {
                Self::Source(::buffa::alloc::boxed::Box::new(v))
            }
        }
        impl From<super::super::super::super::module::input::Source>
        for ::core::option::Option<Input> {
            fn from(v: super::super::super::super::module::input::Source) -> Self {
                Self::Some(Input::from(v))
            }
        }
        impl From<super::super::super::super::module::input::Map> for Input {
            fn from(v: super::super::super::super::module::input::Map) -> Self {
                Self::Map(::buffa::alloc::boxed::Box::new(v))
            }
        }
        impl From<super::super::super::super::module::input::Map>
        for ::core::option::Option<Input> {
            fn from(v: super::super::super::super::module::input::Map) -> Self {
                Self::Some(Input::from(v))
            }
        }
        impl From<super::super::super::super::module::input::Store> for Input {
            fn from(v: super::super::super::super::module::input::Store) -> Self {
                Self::Store(::buffa::alloc::boxed::Box::new(v))
            }
        }
        impl From<super::super::super::super::module::input::Store>
        for ::core::option::Option<Input> {
            fn from(v: super::super::super::super::module::input::Store) -> Self {
                Self::Some(Input::from(v))
            }
        }
        impl From<super::super::super::super::module::input::Params> for Input {
            fn from(v: super::super::super::super::module::input::Params) -> Self {
                Self::Params(::buffa::alloc::boxed::Box::new(v))
            }
        }
        impl From<super::super::super::super::module::input::Params>
        for ::core::option::Option<Input> {
            fn from(v: super::super::super::super::module::input::Params) -> Self {
                Self::Some(Input::from(v))
            }
        }
        impl From<super::super::super::super::module::FoundationalStore> for Input {
            fn from(v: super::super::super::super::module::FoundationalStore) -> Self {
                Self::FoundationalStore(::buffa::alloc::boxed::Box::new(v))
            }
        }
        impl From<super::super::super::super::module::FoundationalStore>
        for ::core::option::Option<Input> {
            fn from(v: super::super::super::super::module::FoundationalStore) -> Self {
                Self::Some(Input::from(v))
            }
        }
    }
}
