// @generated by buffa-codegen. DO NOT EDIT.

include!("sf.substreams.foundational-store.service.v1.service.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.substreams.foundational-store.service.v1.service.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.substreams.foundational-store.service.v1.service.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::GetRequestView;
#[doc(inline)]
pub use self::__buffa::view::GetRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::GetRequestLazyView;
#[doc(inline)]
pub use self::__buffa::view::GetResponseView;
#[doc(inline)]
pub use self::__buffa::view::GetResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::GetResponseLazyView;
#[doc(inline)]
pub use self::__buffa::view::GetAllRequestView;
#[doc(inline)]
pub use self::__buffa::view::GetAllRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::GetAllRequestLazyView;
#[doc(inline)]
pub use self::__buffa::view::ResponseEntryView;
#[doc(inline)]
pub use self::__buffa::view::ResponseEntryOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ResponseEntryLazyView;
#[doc(inline)]
pub use self::__buffa::view::GetAllResponseView;
#[doc(inline)]
pub use self::__buffa::view::GetAllResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::GetAllResponseLazyView;
#[doc(inline)]
pub use self::__buffa::view::EntryView;
#[doc(inline)]
pub use self::__buffa::view::EntryOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::EntryLazyView;
#[doc(inline)]
pub use self::__buffa::view::EntriesView;
#[doc(inline)]
pub use self::__buffa::view::EntriesOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::EntriesLazyView;
