// @generated by buffa-codegen. DO NOT EDIT.
// source: sf/substreams/foundational-store/service/v2/service.proto

/// GetRequest specifies the parameters for retrieving values from the store.
/// Used by both Get and GetFirst operations to query the foundational store.
#[derive(Clone, Debug, Default)]
pub struct GetRequestView<'a> {
    /// The block number at which to query the data.
    /// This ensures queries are performed against a specific point in the blockchain history.
    ///
    /// Field 1: `block_number`
    pub block_number: u64,
    /// The block hash for additional verification and fork-awareness.
    /// Ensures the query is performed against the correct block in case of chain forks.
    ///
    /// Field 2: `block_hash`
    pub block_hash: &'a [u8],
    /// The keys to retrieve from the store.
    /// For Get: exact key matches are returned.
    /// For GetFirst: the first key \>= each requested key is returned (lexicographically).
    ///
    /// Field 3: `keys`
    pub keys: ::buffa::RepeatedView<
        'a,
        super::super::super::super::model::v2::__buffa::view::KeyView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for GetRequestView<'a> {
    type Owned = super::super::GetRequest;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_number = ::buffa::types::decode_uint64(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.block_hash = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::super::super::model::v2::__buffa::view::KeyView,
                    >(),
                )?;
                view.keys
                    .push(
                        <super::super::super::super::model::v2::__buffa::view::KeyView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::GetRequest, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::GetRequest, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::GetRequest {
            block_number: self.block_number,
            block_hash: (self.block_hash).to_vec(),
            keys: self
                .keys
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for GetRequestView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.block_number != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_number) as u64;
        }
        if !self.block_hash.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.block_hash) as u64;
        }
        for v in &self.keys {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.block_number != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.block_number, buf);
        }
        if !self.block_hash.is_empty() {
            ::buffa::types::put_shared_bytes_field(2u32, &self.block_hash, buf);
        }
        for v in &self.keys {
            ::buffa::types::put_len_delimited_header(
                3u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for GetRequestView<'a> {
    const PACKAGE: &'static str = "sf.substreams.foundational_store.service.v2";
    const NAME: &'static str = "GetRequest";
    const FULL_NAME: &'static str = "sf.substreams.foundational_store.service.v2.GetRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.foundational_store.service.v2.GetRequest";
}
::buffa::impl_default_view_instance!(GetRequestView);
::buffa::impl_view_reborrow!(GetRequestView);
/** Self-contained, `'static` owned view of a `GetRequest` message.

 Wraps [`::buffa::OwnedView`]`<`[`GetRequestView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`GetRequestView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct GetRequestOwnedView(::buffa::OwnedView<GetRequestView<'static>>);
impl GetRequestOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            GetRequestOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            GetRequestOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::GetRequest,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            GetRequestOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`GetRequestView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &GetRequestView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::GetRequest {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// The block number at which to query the data.
    /// This ensures queries are performed against a specific point in the blockchain history.
    ///
    /// Field 1: `block_number`
    #[must_use]
    pub fn block_number(&self) -> u64 {
        self.0.reborrow().block_number
    }
    /// The block hash for additional verification and fork-awareness.
    /// Ensures the query is performed against the correct block in case of chain forks.
    ///
    /// Field 2: `block_hash`
    #[must_use]
    pub fn block_hash(&self) -> &'_ [u8] {
        self.0.reborrow().block_hash
    }
    /// The keys to retrieve from the store.
    /// For Get: exact key matches are returned.
    /// For GetFirst: the first key \>= each requested key is returned (lexicographically).
    ///
    /// Field 3: `keys`
    #[must_use]
    pub fn keys(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::super::super::model::v2::__buffa::view::KeyView<'_>,
    > {
        &self.0.reborrow().keys
    }
}
impl ::core::convert::From<::buffa::OwnedView<GetRequestView<'static>>>
for GetRequestOwnedView {
    fn from(inner: ::buffa::OwnedView<GetRequestView<'static>>) -> Self {
        GetRequestOwnedView(inner)
    }
}
impl ::core::convert::From<GetRequestOwnedView>
for ::buffa::OwnedView<GetRequestView<'static>> {
    fn from(wrapper: GetRequestOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<GetRequestView<'static>>>
for GetRequestOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<GetRequestView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::GetRequest {
    type View<'a> = GetRequestView<'a>;
    type ViewHandle = GetRequestOwnedView;
}
/// GetResponse contains the results of a store query operation.
/// Provides batch results for multiple keys with consistent block-level metadata.
#[derive(Clone, Debug, Default)]
pub struct GetResponseView<'a> {
    /// Indicates whether the requested block has been processed by the store.
    /// When false, some entries may not be available even if they should exist.
    ///
    /// Field 1: `block_reached`
    pub block_reached: bool,
    /// The query results for each requested key.
    /// Each entry corresponds to one of the keys in the request, in the same order.
    ///
    /// Field 2: `entries`
    pub entries: ::buffa::MessageFieldView<
        super::super::super::super::model::v2::__buffa::view::QueriedEntriesView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for GetResponseView<'a> {
    type Owned = super::super::GetResponse;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_reached = ::buffa::types::decode_bool(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                match view.entries.as_mut() {
                    Some(existing) => {
                        ::buffa::MessageView::merge_into_view(existing, sub, __sub_ctx)?
                    }
                    None => {
                        view.entries = ::buffa::MessageFieldView::set(
                            <super::super::super::super::model::v2::__buffa::view::QueriedEntriesView as ::buffa::MessageView>::decode_view_ctx(
                                sub,
                                __sub_ctx,
                            )?,
                        );
                    }
                }
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::GetResponse, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::GetResponse, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::GetResponse {
            block_reached: self.block_reached,
            entries: match self.entries.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        super::super::super::super::model::v2::QueriedEntries,
                        ::buffa::Inline<
                            super::super::super::super::model::v2::QueriedEntries,
                        >,
                    >::some(v.to_owned_from_source(__buffa_src)?)
                }
                None => ::buffa::MessageField::none(),
            },
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for GetResponseView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.block_reached {
            size += 1u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        if self.entries.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.entries.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.block_reached {
            ::buffa::types::put_bool_field(1u32, self.block_reached, buf);
        }
        if self.entries.is_set() {
            ::buffa::types::put_len_delimited_header(
                2u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.entries.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for GetResponseView<'a> {
    const PACKAGE: &'static str = "sf.substreams.foundational_store.service.v2";
    const NAME: &'static str = "GetResponse";
    const FULL_NAME: &'static str = "sf.substreams.foundational_store.service.v2.GetResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.foundational_store.service.v2.GetResponse";
}
::buffa::impl_default_view_instance!(GetResponseView);
::buffa::impl_view_reborrow!(GetResponseView);
/** Self-contained, `'static` owned view of a `GetResponse` message.

 Wraps [`::buffa::OwnedView`]`<`[`GetResponseView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`GetResponseView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct GetResponseOwnedView(::buffa::OwnedView<GetResponseView<'static>>);
impl GetResponseOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            GetResponseOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            GetResponseOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::GetResponse,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            GetResponseOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`GetResponseView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &GetResponseView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::GetResponse {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Indicates whether the requested block has been processed by the store.
    /// When false, some entries may not be available even if they should exist.
    ///
    /// Field 1: `block_reached`
    #[must_use]
    pub fn block_reached(&self) -> bool {
        self.0.reborrow().block_reached
    }
    /// The query results for each requested key.
    /// Each entry corresponds to one of the keys in the request, in the same order.
    ///
    /// Field 2: `entries`
    #[must_use]
    pub fn entries(
        &self,
    ) -> &::buffa::MessageFieldView<
        super::super::super::super::model::v2::__buffa::view::QueriedEntriesView<'_>,
    > {
        &self.0.reborrow().entries
    }
}
impl ::core::convert::From<::buffa::OwnedView<GetResponseView<'static>>>
for GetResponseOwnedView {
    fn from(inner: ::buffa::OwnedView<GetResponseView<'static>>) -> Self {
        GetResponseOwnedView(inner)
    }
}
impl ::core::convert::From<GetResponseOwnedView>
for ::buffa::OwnedView<GetResponseView<'static>> {
    fn from(wrapper: GetResponseOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<GetResponseView<'static>>>
for GetResponseOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<GetResponseView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::GetResponse {
    type View<'a> = GetResponseView<'a>;
    type ViewHandle = GetResponseOwnedView;
}
