// @generated by buffa-codegen. DO NOT EDIT.
// source: sf/substreams/v1/clock.proto

/** Lazy view of `sf.substreams.v1.Clock`: nested and repeated message fields are
 recorded as undecoded byte ranges and decoded on access. See
 [`::buffa::LazyMessageView`] for the deferred-validation contract;
 the eager, whole-tree-validated counterpart is named `ClockView`.

 Oneof variants, map values, groups, and extern-typed fields (e.g.
 well-known types) hold eagerly-decoded `ClockView`-family
 types; only singular/repeated message fields defer.

 # Examples

 ```rust,ignore
 use buffa::LazyMessageView;

 let view = ClockLazyView::decode_lazy(&bytes)?;
 ```*/
#[derive(Clone, Debug, Default)]
pub struct ClockLazyView<'a> {
    /// Field 1: `id`
    pub id: &'a str,
    /// Field 2: `number`
    pub number: u64,
    /// Field 3: `timestamp`
    pub timestamp: ::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'a>,
    >,
}
impl<'a> ClockLazyView<'a> {
    /// Decode from `buf` under the limits carried by `ctx`, recording
    /// nested/repeated message fields as byte ranges.
    ///
    /// **Not part of the public API.**
    #[doc(hidden)]
    pub fn _decode_lazy_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let mut view = Self::default();
        view._merge_lazy(buf, ctx)?;
        ::core::result::Result::Ok(view)
    }
    /// Merge fields from `buf` into this view (proto merge semantics;
    /// deferred message fragments accumulate).
    ///
    /// **Not part of the public API.**
    #[doc(hidden)]
    pub fn _merge_lazy(
        &mut self,
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur: &'a [u8] = buf;
        while !cur.is_empty() {
            let tag = ::buffa::encoding::Tag::decode(&mut cur)?;
            match tag.field_number() {
                1u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    view.id = ::buffa::types::borrow_str(&mut cur)?;
                }
                2u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::Varint,
                    )?;
                    view.number = ::buffa::types::decode_uint64(&mut cur)?;
                }
                3u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    let __sub_ctx = ctx.descend()?;
                    let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                    match view.timestamp.as_mut() {
                        Some(existing) => {
                            ::buffa::MessageView::merge_into_view(
                                existing,
                                sub,
                                __sub_ctx,
                            )?
                        }
                        None => {
                            view.timestamp = ::buffa::MessageFieldView::set(
                                <::buffa_types::google::protobuf::__buffa::view::TimestampView as ::buffa::MessageView>::decode_view_ctx(
                                    sub,
                                    __sub_ctx,
                                )?,
                            );
                        }
                    }
                }
                _ => {
                    ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                }
            }
        }
        ::core::result::Result::Ok(())
    }
}
impl<'a> ::buffa::LazyMessageView<'a> for ClockLazyView<'a> {
    type Owned = super::super::Clock;
    fn decode_lazy(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        Self::_decode_lazy_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_lazy_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        Self::_decode_lazy_ctx(buf, ctx)
    }
    fn merge_lazy(
        &mut self,
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        self._merge_lazy(buf, ctx)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Clock, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        #[allow(unused_imports)]
        use ::buffa::MessageView as _;
        let __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes> = ::core::option::Option::None;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Clock {
            id: self.id.to_string(),
            number: self.number,
            timestamp: match self.timestamp.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        ::buffa_types::google::protobuf::Timestamp,
                        ::buffa::Inline<::buffa_types::google::protobuf::Timestamp>,
                    >::some(v.to_owned_from_source(__buffa_src)?)
                }
                None => ::buffa::MessageField::none(),
            },
            ..::core::default::Default::default()
        })
    }
}
/// Re-encoding: recorded fragments are replayed byte-for-byte
/// **without validation** — wire-equivalent to the merged value, and
/// a never-accessed malformed deferred field round-trips silently.
/// Inherent rather than [`::buffa::ViewEncode`] (whose `MessageView`
/// supertrait carries the eager whole-tree-validated contract); the
/// fuller `ViewEncode` set (`encode_length_delimited`,
/// `encode_with_cache`) lives on the eager view.
impl<'a> ClockLazyView<'a> {
    /// Compute the encoded byte size, filling `cache` with
    /// per-message sizes consumed by a following `write_to` call.
    /// Called for that side effect by `encode`; prefer `encoded_len`
    /// when only the size is needed.
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    pub fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        #[allow(unused_imports)]
        use ::buffa::ViewEncode as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if self.number != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.number) as u64;
        }
        if self.timestamp.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.timestamp.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    /// Write the encoded bytes to `buf`, reading per-message sizes
    /// from the `cache` filled by a preceding `compute_size` call.
    /// Prefer `encode` unless threading a shared cache.
    #[allow(clippy::needless_borrow)]
    pub fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        #[allow(unused_imports)]
        use ::buffa::ViewEncode as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if self.number != 0u64 {
            ::buffa::types::put_uint64_field(2u32, self.number, buf);
        }
        if self.timestamp.is_set() {
            ::buffa::types::put_len_delimited_header(
                3u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.timestamp.write_to(__cache, buf);
        }
    }
    /// Compute size, then write. Primary encode entry point.
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encode`](Self::try_encode) for the error-returning
    /// variant.
    #[inline]
    pub fn encode(&self, buf: &mut impl ::buffa::EncodeSink) {
        self.try_encode(buf).unwrap_or_else(|_| ::buffa::encode_size_overflow())
    }
    /// Encode, returning an error instead of panicking if the
    /// encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// On `Err`, nothing is written to `buf`.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    pub fn try_encode(
        &self,
        buf: &mut impl ::buffa::EncodeSink,
    ) -> ::core::result::Result<(), ::buffa::EncodeError> {
        let mut __cache = ::buffa::SizeCache::new();
        ::buffa::checked_encode_size(self.compute_size(&mut __cache))?;
        self.write_to(&mut __cache, buf);
        ::core::result::Result::Ok(())
    }
    /// Encoded byte size of this view.
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encoded_len`](Self::try_encoded_len) for the
    /// error-returning variant.
    #[inline]
    #[must_use]
    pub fn encoded_len(&self) -> u32 {
        self.try_encoded_len().unwrap_or_else(|_| ::buffa::encode_size_overflow())
    }
    /// Encoded byte size, returning an error instead of panicking
    /// if it exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    pub fn try_encoded_len(&self) -> ::core::result::Result<u32, ::buffa::EncodeError> {
        ::buffa::checked_encode_size(self.compute_size(&mut ::buffa::SizeCache::new()))
    }
    /// Encode this view to a new `Vec<u8>`.
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encode_to_vec`](Self::try_encode_to_vec) for the
    /// error-returning variant. In debug builds, also panics if the
    /// two encode passes disagree on the byte count.
    #[inline]
    #[must_use]
    pub fn encode_to_vec(&self) -> ::buffa::alloc::vec::Vec<u8> {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = match ::buffa::checked_encode_size(
            self.compute_size(&mut __cache),
        ) {
            ::core::result::Result::Ok(__size) => __size as usize,
            ::core::result::Result::Err(_) => ::buffa::encode_size_overflow(),
        };
        let mut __buf = ::buffa::alloc::vec::Vec::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        __buf
    }
    /// Encode to a new `Vec<u8>`, returning an error instead of
    /// panicking if the encoded size exceeds the 2 GiB protobuf
    /// limit ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    ///
    /// # Panics
    ///
    /// In debug builds, panics if the two encode passes disagree
    /// on the byte count.
    pub fn try_encode_to_vec(
        &self,
    ) -> ::core::result::Result<::buffa::alloc::vec::Vec<u8>, ::buffa::EncodeError> {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = ::buffa::checked_encode_size(self.compute_size(&mut __cache))?
            as usize;
        let mut __buf = ::buffa::alloc::vec::Vec::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        ::core::result::Result::Ok(__buf)
    }
    /// Encode this view to a new [`::buffa::bytes::Bytes`].
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encode_to_bytes`](Self::try_encode_to_bytes) for the
    /// error-returning variant. In debug builds, also panics if the
    /// two encode passes disagree on the byte count.
    #[inline]
    #[must_use]
    pub fn encode_to_bytes(&self) -> ::buffa::bytes::Bytes {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = match ::buffa::checked_encode_size(
            self.compute_size(&mut __cache),
        ) {
            ::core::result::Result::Ok(__size) => __size as usize,
            ::core::result::Result::Err(_) => ::buffa::encode_size_overflow(),
        };
        let mut __buf = ::buffa::bytes::BytesMut::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        __buf.freeze()
    }
    /// Encode to a new [`::buffa::bytes::Bytes`], returning an
    /// error instead of panicking if the encoded size exceeds the
    /// 2 GiB protobuf limit ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    ///
    /// # Panics
    ///
    /// In debug builds, panics if the two encode passes disagree
    /// on the byte count.
    pub fn try_encode_to_bytes(
        &self,
    ) -> ::core::result::Result<::buffa::bytes::Bytes, ::buffa::EncodeError> {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = ::buffa::checked_encode_size(self.compute_size(&mut __cache))?
            as usize;
        let mut __buf = ::buffa::bytes::BytesMut::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        ::core::result::Result::Ok(__buf.freeze())
    }
}
impl<'a> ::buffa::MessageName for ClockLazyView<'a> {
    const PACKAGE: &'static str = "sf.substreams.v1";
    const NAME: &'static str = "Clock";
    const FULL_NAME: &'static str = "sf.substreams.v1.Clock";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.v1.Clock";
}
/** Lazy view of `sf.substreams.v1.BlockRef`: nested and repeated message fields are
 recorded as undecoded byte ranges and decoded on access. See
 [`::buffa::LazyMessageView`] for the deferred-validation contract;
 the eager, whole-tree-validated counterpart is named `BlockRefView`.

 Oneof variants, map values, groups, and extern-typed fields (e.g.
 well-known types) hold eagerly-decoded `BlockRefView`-family
 types; only singular/repeated message fields defer.

 # Examples

 ```rust,ignore
 use buffa::LazyMessageView;

 let view = BlockRefLazyView::decode_lazy(&bytes)?;
 ```*/
#[derive(Clone, Debug, Default)]
pub struct BlockRefLazyView<'a> {
    /// Field 1: `id`
    pub id: &'a str,
    /// Field 2: `number`
    pub number: u64,
}
impl<'a> BlockRefLazyView<'a> {
    /// Decode from `buf` under the limits carried by `ctx`, recording
    /// nested/repeated message fields as byte ranges.
    ///
    /// **Not part of the public API.**
    #[doc(hidden)]
    pub fn _decode_lazy_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let mut view = Self::default();
        view._merge_lazy(buf, ctx)?;
        ::core::result::Result::Ok(view)
    }
    /// Merge fields from `buf` into this view (proto merge semantics;
    /// deferred message fragments accumulate).
    ///
    /// **Not part of the public API.**
    #[doc(hidden)]
    pub fn _merge_lazy(
        &mut self,
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur: &'a [u8] = buf;
        while !cur.is_empty() {
            let tag = ::buffa::encoding::Tag::decode(&mut cur)?;
            match tag.field_number() {
                1u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    view.id = ::buffa::types::borrow_str(&mut cur)?;
                }
                2u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::Varint,
                    )?;
                    view.number = ::buffa::types::decode_uint64(&mut cur)?;
                }
                _ => {
                    ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                }
            }
        }
        ::core::result::Result::Ok(())
    }
}
impl<'a> ::buffa::LazyMessageView<'a> for BlockRefLazyView<'a> {
    type Owned = super::super::BlockRef;
    fn decode_lazy(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        Self::_decode_lazy_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_lazy_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        Self::_decode_lazy_ctx(buf, ctx)
    }
    fn merge_lazy(
        &mut self,
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        self._merge_lazy(buf, ctx)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::BlockRef, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        #[allow(unused_imports)]
        use ::buffa::MessageView as _;
        let __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes> = ::core::option::Option::None;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::BlockRef {
            id: self.id.to_string(),
            number: self.number,
            ..::core::default::Default::default()
        })
    }
}
/// Re-encoding: recorded fragments are replayed byte-for-byte
/// **without validation** — wire-equivalent to the merged value, and
/// a never-accessed malformed deferred field round-trips silently.
/// Inherent rather than [`::buffa::ViewEncode`] (whose `MessageView`
/// supertrait carries the eager whole-tree-validated contract); the
/// fuller `ViewEncode` set (`encode_length_delimited`,
/// `encode_with_cache`) lives on the eager view.
impl<'a> BlockRefLazyView<'a> {
    /// Compute the encoded byte size, filling `cache` with
    /// per-message sizes consumed by a following `write_to` call.
    /// Called for that side effect by `encode`; prefer `encoded_len`
    /// when only the size is needed.
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    pub fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        #[allow(unused_imports)]
        use ::buffa::ViewEncode as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if self.number != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.number) as u64;
        }
        ::buffa::saturate_size(size)
    }
    /// Write the encoded bytes to `buf`, reading per-message sizes
    /// from the `cache` filled by a preceding `compute_size` call.
    /// Prefer `encode` unless threading a shared cache.
    #[allow(clippy::needless_borrow)]
    pub fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        #[allow(unused_imports)]
        use ::buffa::ViewEncode as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if self.number != 0u64 {
            ::buffa::types::put_uint64_field(2u32, self.number, buf);
        }
    }
    /// Compute size, then write. Primary encode entry point.
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encode`](Self::try_encode) for the error-returning
    /// variant.
    #[inline]
    pub fn encode(&self, buf: &mut impl ::buffa::EncodeSink) {
        self.try_encode(buf).unwrap_or_else(|_| ::buffa::encode_size_overflow())
    }
    /// Encode, returning an error instead of panicking if the
    /// encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// On `Err`, nothing is written to `buf`.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    pub fn try_encode(
        &self,
        buf: &mut impl ::buffa::EncodeSink,
    ) -> ::core::result::Result<(), ::buffa::EncodeError> {
        let mut __cache = ::buffa::SizeCache::new();
        ::buffa::checked_encode_size(self.compute_size(&mut __cache))?;
        self.write_to(&mut __cache, buf);
        ::core::result::Result::Ok(())
    }
    /// Encoded byte size of this view.
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encoded_len`](Self::try_encoded_len) for the
    /// error-returning variant.
    #[inline]
    #[must_use]
    pub fn encoded_len(&self) -> u32 {
        self.try_encoded_len().unwrap_or_else(|_| ::buffa::encode_size_overflow())
    }
    /// Encoded byte size, returning an error instead of panicking
    /// if it exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    pub fn try_encoded_len(&self) -> ::core::result::Result<u32, ::buffa::EncodeError> {
        ::buffa::checked_encode_size(self.compute_size(&mut ::buffa::SizeCache::new()))
    }
    /// Encode this view to a new `Vec<u8>`.
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encode_to_vec`](Self::try_encode_to_vec) for the
    /// error-returning variant. In debug builds, also panics if the
    /// two encode passes disagree on the byte count.
    #[inline]
    #[must_use]
    pub fn encode_to_vec(&self) -> ::buffa::alloc::vec::Vec<u8> {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = match ::buffa::checked_encode_size(
            self.compute_size(&mut __cache),
        ) {
            ::core::result::Result::Ok(__size) => __size as usize,
            ::core::result::Result::Err(_) => ::buffa::encode_size_overflow(),
        };
        let mut __buf = ::buffa::alloc::vec::Vec::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        __buf
    }
    /// Encode to a new `Vec<u8>`, returning an error instead of
    /// panicking if the encoded size exceeds the 2 GiB protobuf
    /// limit ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    ///
    /// # Panics
    ///
    /// In debug builds, panics if the two encode passes disagree
    /// on the byte count.
    pub fn try_encode_to_vec(
        &self,
    ) -> ::core::result::Result<::buffa::alloc::vec::Vec<u8>, ::buffa::EncodeError> {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = ::buffa::checked_encode_size(self.compute_size(&mut __cache))?
            as usize;
        let mut __buf = ::buffa::alloc::vec::Vec::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        ::core::result::Result::Ok(__buf)
    }
    /// Encode this view to a new [`::buffa::bytes::Bytes`].
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encode_to_bytes`](Self::try_encode_to_bytes) for the
    /// error-returning variant. In debug builds, also panics if the
    /// two encode passes disagree on the byte count.
    #[inline]
    #[must_use]
    pub fn encode_to_bytes(&self) -> ::buffa::bytes::Bytes {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = match ::buffa::checked_encode_size(
            self.compute_size(&mut __cache),
        ) {
            ::core::result::Result::Ok(__size) => __size as usize,
            ::core::result::Result::Err(_) => ::buffa::encode_size_overflow(),
        };
        let mut __buf = ::buffa::bytes::BytesMut::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        __buf.freeze()
    }
    /// Encode to a new [`::buffa::bytes::Bytes`], returning an
    /// error instead of panicking if the encoded size exceeds the
    /// 2 GiB protobuf limit ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    ///
    /// # Panics
    ///
    /// In debug builds, panics if the two encode passes disagree
    /// on the byte count.
    pub fn try_encode_to_bytes(
        &self,
    ) -> ::core::result::Result<::buffa::bytes::Bytes, ::buffa::EncodeError> {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = ::buffa::checked_encode_size(self.compute_size(&mut __cache))?
            as usize;
        let mut __buf = ::buffa::bytes::BytesMut::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        ::core::result::Result::Ok(__buf.freeze())
    }
}
impl<'a> ::buffa::MessageName for BlockRefLazyView<'a> {
    const PACKAGE: &'static str = "sf.substreams.v1";
    const NAME: &'static str = "BlockRef";
    const FULL_NAME: &'static str = "sf.substreams.v1.BlockRef";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.v1.BlockRef";
}
